In [5]:
#imports
import urllib.request
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
#crawling data from wikipedia with bs4
URL="https://en.wikipedia.org/wiki/List_of_airlines_of_the_United_States"
Page = urllib.request.urlopen(URL)
Soup = BeautifulSoup(Page, "lxml")
Right_table=Soup.find_all('table', class_='wikitable')
A=[]
B=[]
C=[]
D=[]
E=[]
F=[]
G=[]
for row in Right_table[0].findAll('tr'):
    cells=row.findAll('td')
    if len(cells)==8:
        A.append(cells[0].find(text=True))
        B.append(cells[2].find(text=True))
        C.append(cells[3].find(text=True))
        D.append(cells[4].find(text=True))
        E.append(cells[5].find(text=True))
        F.append(cells[6].find(text=True))
        G.append(cells[7].find(text=True))

In [7]:
df=pd.DataFrame(A,columns=['Airline'])
df['IATA']=B
df['ICAO']=C
df['Callsign']=D
df['Primary Hubs, Secondary Hubs']=E
df['Founded']=F
df['Notes']=G
df = df.replace('\n','', regex=True)
df.to_csv("Airplane_Data.csv")
df

,Airline,IATA,ICAO,Callsign,"Primary Hubs, Secondary Hubs",Founded,Notes
0,Alaska Airlines,AS,ASA,ALASKA,Seattle/Tacoma,1932,Founded as McGee Airways and commenced operati...
1,Allegiant Air,G4,AAY,ALLEGIANT,Las Vegas,1997,Founded as WestJet Express and commenced opera...
2,American Airlines,AA,AAL,AMERICAN,Dallas/Fort Worth,1926,Founded as American Airways and commenced oper...
3,Avelo Airlines,XP,VXP,AVELO,Burbank,1987,First did business as Casino Express Airlines ...
4,Breeze Airways,MX,MXY,MOXY,,2018,
5,Delta Air Lines,DL,DAL,DELTA,Atlanta,1924,Founded as Huff Daland Dusters and commenced o...
6,"Eastern Airlines, LLC",2D,EAL,EASTERN,Miami,2010,
7,Frontier Airlines,F9,FFT,FRONTIER FLIGHT,Denver,1994,
8,Hawaiian Airlines,HA,HAL,HAWAIIAN,Honolulu,1929,Founded as Inter-Island Airways in early 1929 ...
9,JetBlue,B6,JBU,JETBLUE,New York-JFK,1998,Founded as New Air and commenced operations in...
10,Southwest Airlines,WN,SWA,SOUTHWEST,Dallas-Love,1967,Founded as Air Southwest and commenced operati...
11,Spirit Airlines,NK,NKS,SPIRIT WINGS,Atlantic City,1980,Founded as Charter One.
12,Sun Country Airlines,SY,SCX,SUN COUNTRY,Minneapolis/St. Paul,1982,Commenced operations in 1983.
13,United Airlines,UA,UAL,UNITED,Chicago-O'Hare,1926,Founded as Varney Air Lines and commenced oper...